// <auto-generated />
namespace Grading_SOH_Final_Rel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addstd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstd));
        
        string IMigrationMetadata.Id
        {
            get { return "201612301654578_addstd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
